<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OFARIN S</title>
    <link rel="stylesheet" href="ofarin.css">
</head>
<body>
    
</body>
</html>
<h1>OFARIN SURXON</h1>
<hr>
<div class="photo"> 
<img src="https://yt3.googleusercontent.com/dp42iLM5iaHrXkLT0aAN5NX3fpIrE6Y-mIshVEPUHEH2EijCltqT0gTgCkxq8PqbBIlNmMqUYhQ=s176-c-k-c0x00ffffff-no-rj" alt=""></div>
<div class="vid"><video src="file:///C:/Users/Alibek/AppData/Local/CapCut/Videos/0727.mp4" autoplay muted loop ></video></div>
